using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using recycle.Domain;

namespace recycle.Infrastructure.Configurations
{
    public class ReviewConfiguration : IEntityTypeConfiguration<Review>
    {
        public void Configure(EntityTypeBuilder<Review> builder)
        {
            // Table Name
            builder.ToTable("Reviews");

            // Primary Key
            builder.HasKey(r => r.ReviewId);

            builder.Property(r => r.ReviewId)
                .ValueGeneratedNever(); // Generated by app (Guid.NewGuid())

            // Property Configurations
            builder.Property(r => r.RequestId)
                .IsRequired();

            builder.Property(r => r.ReviewerId)
                .IsRequired();

            builder.Property(r => r.RevieweeId)
                .IsRequired();

            builder.Property(r => r.Rating)
                .IsRequired();

            builder.Property(r => r.Comment)
                .HasMaxLength(500)
                .IsUnicode(true);

            builder.Property(r => r.FlagReason)
                .HasMaxLength(200)
                .IsUnicode(true);

            builder.Property(r => r.CreatedAt)
                .IsRequired()
                .HasDefaultValueSql("GETUTCDATE()");

            builder.Property(r => r.UpdatedAt)
                .IsRequired(false);

            builder.Property(r => r.IsEdited)
                .HasDefaultValue(false);

            builder.Property(r => r.IsFlagged)
                .HasDefaultValue(false);

            builder.Property(r => r.IsHidden)
                .HasDefaultValue(false);

            builder.Property(r => r.FlaggedAt)
                .IsRequired(false);

            // Relationships
            builder.HasOne(r => r.PickupRequest)
                .WithOne(pr => pr.Review)
                .HasForeignKey<Review>(r => r.RequestId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_Reviews_PickupRequests");

            builder.HasOne(r => r.Reviewer)
                .WithMany(u => u.ReviewsGiven)
                .HasForeignKey(r => r.ReviewerId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_Reviews_Reviewer");

            builder.HasOne(r => r.Reviewee)
                .WithMany(u => u.ReviewsReceived)
                .HasForeignKey(r => r.RevieweeId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_Reviews_Reviewee");

            // Indexes
            builder.HasIndex(r => r.RequestId)
                .IsUnique()
                .HasDatabaseName("IX_Reviews_RequestId_Unique");

            builder.HasIndex(r => r.ReviewerId)
                .HasDatabaseName("IX_Reviews_ReviewerId");

            builder.HasIndex(r => r.RevieweeId)
                .HasDatabaseName("IX_Reviews_RevieweeId");

            builder.HasIndex(r => r.CreatedAt)
                .HasDatabaseName("IX_Reviews_CreatedAt");

            // Check Constraints
            builder.HasCheckConstraint("CHK_Reviews_NotSelfReview", "[ReviewerId] <> [RevieweeId]");
            builder.HasCheckConstraint("CHK_Reviews_RatingRange", "[Rating] BETWEEN 1 AND 5");
        }
    }
}
